# server
server:
  port: 9090

# mysql
datasource:
  username: xxxx
  password:  xxxx
  host: xxxx
  port: xxx
  database: xxxx
  charset: utf8mb4
  parseTime: true
  loc: Asia/Shanghai


#redis
# connection_mode 连接方式，0 为单机模式，1 为集群模式
redis:
  connection_mode : 0
  addr : ['xxxx:xxxx']
  password : ''
  db : 0

# email
email:
  alias: xxxxx
  host: smtp.163.com # 网易邮箱
  port: 465
  username: xxxxx@163.com
  password: xxxxx

# jwt
jwt:
  expired_time: 86400
  prefix: library_jwt
  sign_key : library_jwt