# server
server:
  port: 9090

# mysql
datasource:
  username: root
  password:  fhw8612.
  host: 127.0.0.1
  port: 3306
  database: library_1
  charset: utf8mb4
  parseTime: true
  loc: Asia/Shanghai

# email
email:
  alias: xxxxx
  host: smtp.163.com # 网易邮箱
  port: 465
  username: xxxxx@163.com
  password: xxxxx
